meta_product_name: "CycleThru"
meta_title: "Join CycleThru a global community of touring cyclist"
meta_description: "Let us help you plan your next adventure"
meta_image: "logogreen.png" # should exist in `app/assets/images/`

